const registrationFormConfig = [
  {
    dataType:"title",
    formLabel:"!REGISTRATION_FORM_TITLE"
  },
  {
    dataType:"text",
    formValue:"FirstName",
    formLabel:"!REGISTRATION_FORM_FirstName_LABEL",
    helpText:"!REGISTRATION_FORM_FirstName_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_FirstName_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"text",
    formValue:"MiddleName",
    formLabel:"!REGISTRATION_FORM_MiddleName_LABEL",
    helpText:"!REGISTRATION_FORM_MiddleName_HELPTEXT",
    isRequired:false,
    placeholder:"!REGISTRATION_FORM_MiddleName_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"LastName",
    formLabel:"!REGISTRATION_FORM_LastName_LABEL",
    helpText:"!REGISTRATION_FORM_LastName_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_LastName_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType: "enum",
    formValue: "SchoolName",
    formLabel:"!REGISTRATION_FORM_SchoolName_LABEL",
    helpText:"!REGISTRATION_FORM_SchoolName_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_SchoolName_PLACEHOLDER",
    isRequired: true,
    enableSubFiltering: true,
    filterFields: [
      "Site  Type",
      "Region"
    ],
    valueField: "School Name",
    enumItems: [
      {"Site  Type": 'School', "Region": 'Daly City', "School Name": 'Jefferson Elementary School District'},
      {"Site  Type": 'School', "Region": 'Daly City', "School Name": 'Woodrow Wilson Elementary School'},
      {"Site  Type": 'School', "Region": 'Daly City', "School Name": 'Panorama Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Burbank Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Cherryland Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'East Avenue Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Park Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Stonebrae Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Strobridge Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Cesar Chavez Middle School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'MLK Middle School Hayward'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Winton Middle School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Ochoa Middle School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Bret Harte Hayward Middle School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Longwood Elementary School Hayward'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Palma Ceia Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Glassbrook Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Harder Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Tyrrell Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Fairview Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Treeview Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Schafer Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Bowman Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Eldridge Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Faith Ringgold Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Ruus Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Southgate Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Lorin Eden Elementary School'},
      {"Site  Type": 'School', "Region": 'Hayward', "School Name": 'Eden Gardens Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Coliseum Collegiate Prep Academy'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Montera Middle School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Westlake Middle School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'ASCEND Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Esperanza Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Korematsu Discovery Academy'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Manzanita Community School & Manzanita SEED'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Elmhurst Middle School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Global Family Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Howard Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Sankofa Academy'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Glenview Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Prescott Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Greenleaf Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'EnCompass Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Bridges Academy Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'MLK Lafayette Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'International Community School & Think College Now'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Learning Without Limits Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Bret Harte Oakland Middle School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Madison Park Primary'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Futures Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Futures & Community United Elementary School'},
      {"Site  Type": 'School', "Region": 'Oakland', "School Name": 'Life Academy'},
      {"Site  Type": 'School', "Region": 'Redwood City', "School Name": 'John Gill Elementary School'},
      {"Site  Type": 'School', "Region": 'Redwood City', "School Name": 'Hawes Elementary School'},
      {"Site  Type": 'School', "Region": 'Redwood City', "School Name": 'Henry Ford Elementary School'},
      {"Site  Type": 'School', "Region": 'Redwood City', "School Name": 'Adelante Selby Lane Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Bessie Carmichael'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Redding Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Garfield Elementary School'},
      {"Site  Type": 'Community Center', "Region": 'San Francisco Civic Center', "School Name": 'Up on Top - Program Site'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Sherman Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Moscone Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Tenderloin Community School'},
      {
        "Site  Type": 'Community Center',
        "Region": 'San Francisco Civic Center',
        "School Name": 'Salvation Army Kroc Center - Program Site'
      },
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'John Muir Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'McCoppin Elementary School'},
      {
        "Site  Type": 'Community Center',
        "Region": 'San Francisco Civic Center',
        "School Name": 'Indochinese Housing Development Corporation - Lead Agency'
      },
      {
        "Site  Type": 'Community Center',
        "Region": 'San Francisco Civic Center',
        "School Name": 'Indochinese Housing Development Center - Program Site'
      },
      {"Site  Type": 'School', "Region": 'San Francisco Civic Center', "School Name": 'Cobb School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'El Dorado Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Francisco Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Herbert Hoover Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Kipp Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'San Francisco Community School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'TECA Middle School - Program Site'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Visitation Valley Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Everett Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'MLK Academic Middle School SF'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'KIPP SF Bay Academy Program Site'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'TECA Elementary School - Program Site'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Mission Education Center'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Bryant Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Sanchez Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Lakeshore Alternative Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Alvarado Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Marshall Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Flynn Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Sunnyside Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Hillcrest Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Bret Harte Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'ER Taylor Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Monroe Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Guadalupe Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Paul Revere Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Cleveland Elementary School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Junipero Serra Elementary'},
      {"Site  Type": 'Community Center', "Region": 'San Francisco Crocker', "School Name": 'Mission YMCA Learning Hub'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Paul Revere Middle School'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Bret Harte'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'KIPP SF Bay Academy Lead Agency'},
      {"Site  Type": 'School', "Region": 'San Francisco Crocker', "School Name": 'Willie Brown Middle School'},
      {"Site  Type": 'Community Center', "Region": 'San Francisco Crocker', "School Name": 'Joseph Lee Rec Center Bayview'},
      {"Site  Type": 'Park', "Region": 'San Rafael', "School Name": 'San Rafael All Stars and Laureates'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Coleman Elementary School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Short Elementary School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Bahia Vista Elementary School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Venetia Valley K-8 School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'San Pedro Elementary School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Laurel Dell Elementary School'},
      {"Site  Type": 'School', "Region": 'San Rafael', "School Name": 'Davidson Middle School'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'Ocala Middle School'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'Franklin'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'McKinley'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'Mathson Middle School'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'Washington'},
      {"Site  Type": 'School', "Region": 'San Jose', "School Name": 'Cornerstone Elementary'},
      {"Site  Type": 'Community Center', "Region": 'Other', "School Name": 'Test School'},
      {"Site  Type": 'Community Center', "Region": 'IFC-SF', "School Name": 'IFC San Francisco'}
    ]
  },
  {
    dataType:"email",
    formValue:"PersonalEmail",
    formLabel:"!REGISTRATION_FORM_PersonalEmail_LABEL",
    helpText:"!REGISTRATION_FORM_PersonalEmail_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_PersonalEmail_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"tel",
    formValue:"HomePhone",
    formLabel:"!REGISTRATION_FORM_HomePhone_LABEL",
    helpText:"!REGISTRATION_FORM_HomePhone_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_HomePhone_PLACEHOLDER",
  },
  {
    dataType:"date",
    formValue:"Birthdate",
    formLabel:"!REGISTRATION_FORM_Birthdate_LABEL",
    helpText:"!REGISTRATION_FORM_Birthdate_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Birthdate_PLACEHOLDER",
    min:"1900-01-01",
    max:"2021-04-01",
    isRequired: true
  },
  {
    dataType:"enum",
    formValue:"Gender",
    formLabel:"!REGISTRATION_FORM_Gender_LABEL",
    helpText:"!REGISTRATION_FORM_Gender_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Gender_PLACEHOLDER",
    enumItems: [
      "Male",
      "Female",
      "Non-binary",
      "Prefer not to say"
    ]
  },
  {
    dataType:"enum",
    formValue:"Grade",
    formLabel:"!REGISTRATION_FORM_Grade_LABEL",
    helpText:"!REGISTRATION_FORM_Grade_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Grade_PLACEHOLDER",
    enumItems: [
      "Kindergarten",
      "1st",
      "2nd",
      "3rd",
      "4th",
      "5th",
      "6th",
      "7th",
      "8th"
    ]
  },
  {
    dataType:"enum",
    formValue:"Ethnicity",
    formLabel:"!REGISTRATION_FORM_Ethnicity_LABEL",
    helpText:"!REGISTRATION_FORM_Ethnicity_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Ethnicity_PLACEHOLDER",
    enumItems: [
      "Hispanic/Latino",
      "Native American",
      "African American",
      "Pacific Islander",
      "Asian",
      "Caucasian",
      "Middle Eastern/Arabic",
      "Multi-Racial/Multi-Ethnic",
      "Filipino",
      "Other"
    ]
  },
  {
    dataType:"enum",
    formValue:"ReducedPriceLunch",
    formLabel:"!REGISTRATION_FORM_ReducedPriceLunch_LABEL",
    helpText:"!REGISTRATION_FORM_ReducedPriceLunch_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ReducedPriceLunch_PLACEHOLDER",
    enumItems: [
      "Yes",
      "No"
    ]
  },
  {
    dataType:"textArea",
    formValue:"Allergies",
    formLabel:"!REGISTRATION_FORM_Allergies_LABEL",
    helpText:"!REGISTRATION_FORM_Allergies_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Allergies_PLACEHOLDER",
  },
  {
    dataType:"enum",
    formValue:"PermissiontoCommuteAlone",
    formLabel:"!REGISTRATION_FORM_PermissiontoCommuteAlone_LABEL",
    helpText:"!REGISTRATION_FORM_PermissiontoCommuteAlone_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_PermissiontoCommuteAlone_PLACEHOLDER",
    enumItems: [
      "Yes",
      "No"
    ]
  },
  {
    dataType:"title",
    formLabel:"Parent/Guardian Information"
  },
  {
    dataType:"text",
    formValue:"ParentFName",
    formLabel:"!REGISTRATION_FORM_ParentFName_LABEL",
    helpText:"!REGISTRATION_FORM_ParentFName_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentFName_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"text",
    formValue:"ParentLName",
    formLabel:"!REGISTRATION_FORM_ParentLName_LABEL",
    helpText:"!REGISTRATION_FORM_ParentLName_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentLName_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"email",
    formValue:"ParentEmail",
    formLabel:"!REGISTRATION_FORM_ParentEmail_LABEL",
    helpText:"!REGISTRATION_FORM_ParentEmail_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentEmail_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"text",
    formValue:"Relationship",
    formLabel:"!REGISTRATION_FORM_Relationship_LABEL",
    helpText:"!REGISTRATION_FORM_Relationship_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Relationship_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"ParentPhone1",
    formLabel:"!REGISTRATION_FORM_ParentPhone1_LABEL",
    helpText:"!REGISTRATION_FORM_ParentPhone1_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentPhone1_PLACEHOLDER",
    isRequired: true
  },
  {
    dataType:"tel",
    formValue:"ParentPhone2",
    formLabel:"!REGISTRATION_FORM_ParentPhone2_LABEL",
    helpText:"!REGISTRATION_FORM_ParentPhone2_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentPhone2_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"ParentPhone3",
    formLabel:"!REGISTRATION_FORM_ParentPhone3_LABEL",
    helpText:"!REGISTRATION_FORM_ParentPhone3_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentPhone3_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"MailingStreet",
    formLabel:"!REGISTRATION_FORM_MailingStreet_LABEL",
    helpText:"!REGISTRATION_FORM_MailingStreet_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_MailingStreet_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"MailingCity",
    formLabel:"!REGISTRATION_FORM_MailingCity_LABEL",
    helpText:"!REGISTRATION_FORM_MailingCity_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_MailingCity_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"MailingState",
    formLabel:"!REGISTRATION_FORM_MailingState_LABEL",
    helpText:"!REGISTRATION_FORM_MailingState_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_MailingState_PLACEHOLDER",
  },
  {
    dataType:"number",
    formValue:"MailingZip",
    formLabel:"!REGISTRATION_FORM_MailingZip_LABEL",
    helpText:"!REGISTRATION_FORM_MailingZip_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_MailingZip_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"MailingCountry",
    formLabel:"!REGISTRATION_FORM_MailingCountry_LABEL",
    helpText:"!REGISTRATION_FORM_MailingCountry_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_MailingCountry_PLACEHOLDER",
  },
  {
    dataType:"enum",
    formValue:"ParentEnglishFluency",
    formLabel:"!REGISTRATION_FORM_ParentEnglishFluency_LABEL",
    helpText:"!REGISTRATION_FORM_ParentEnglishFluency_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentEnglishFluency_PLACEHOLDER",
    enumItems: [
      "Yes",
      "Some",
      "No"
    ]
  },
  {
    dataType:"enum",
    formValue:"ParentHomeLang",
    formLabel:"!REGISTRATION_FORM_ParentHomeLang_LABEL",
    helpText:"!REGISTRATION_FORM_ParentHomeLang_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_ParentHomeLang_PLACEHOLDER",
    enumItems: [
      "English",
      "Spanish",
      "Chinese (incl. Cantonese, Mandarin, other Chinese languages)",
      "Arabic",
      "Bengali",
      "French and French Creole",
      "German",
      "Greek",
      "Gujrati",
      "Hebrew",
      "Hindi",
      "Hmong",
      "Italian",
      "Japanese",
      "Korean",
      "Punjabi",
      "Persian",
      "Polish",
      "Portuguese",
      "Russian",
      "Tagalog",
      "Telugu",
      "Urdu",
      "Vietnamese",
      "Other"
    ]
  },
  {
    dataType:"enum",
    formValue:"Volunteer",
    formLabel:"!REGISTRATION_FORM_Volunteer_LABEL",
    helpText:"!REGISTRATION_FORM_Volunteer_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Volunteer_PLACEHOLDER",
    enumItems: [
      "Yes",
      "No"
    ]
  },
  {
    dataType:"title",
    formLabel:"Emergency Contact (Other than Parent/Guardian)"
  },
  {
    dataType:"text",
    formValue:"Emergency_Contact_Name",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Name_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Name_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Name_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"Emergency_Contact_Relationship",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Relationship_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Relationship_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Relationship_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Emergency_Contact_Phone1",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Phone1_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Phone1_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Phone1_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Second_Emergency_Contact_Phone2",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Phone2_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Phone2_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Phone2_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Emergency_Contact_Phone3",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Phone3_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Phone3_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Phone3_PLACEHOLDER",
  },
  {
    dataType:"enum",
    formValue:"Emergency_Contact_Permission_to_Pickup_child",
    formLabel:"!REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_LABEL",
    helpText:"!REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER",
    enumItems: [
      "Yes",
      "No"
    ]
  },
  {
    dataType:"title",
    formLabel:"Second Emergency Contact (Other than Parent/Guardian and Primary Emergency Contact)"
  },
  {
    dataType:"text",
    formValue:"Second_Emergency_Contact_Name",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Name_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Name_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Name_PLACEHOLDER",
  },
  {
    dataType:"text",
    formValue:"Second_Emergency_Contact_Relationship",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Relationship_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Relationship_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Relationship_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Second_Emergency_Contact_Phone1",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone1_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone1_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone1_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Second_Emergency_Contact_Phone2",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone2_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone2_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone2_PLACEHOLDER",
  },
  {
    dataType:"tel",
    formValue:"Second_Emergency_Contact_Phone3",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone3_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone3_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Phone3_PLACEHOLDER",
  },
  {
    dataType: "enum",
    formValue: "Second_Emergency_Contact_Permission_to_Pickup_child",
    formLabel:"!REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_LABEL",
    helpText:"!REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT",
    placeholder:"!REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER",
    enumItems: [
      "Yes",
      "No"
    ]
  }
];

export default registrationFormConfig;
