const localization_en = {

  //Language form
  LANGUAGE_FORM_LABEL_TEXT: "Language",
  LANGUAGE_FORM_HELP_TEXT: "Select Language",
  LANGUAGE_FORM_PLACEHOLDER_TEXT: "Select Language",

  //New or Existing form
  NEW_OR_EXISTING_FORM_LABEL_TEXT: "New or Existing?",
  NEW_OR_EXISTING_FORM_HELP_TEXT: "Select whether you are starting a new student registration or updating an existing student registration",
  NEW_OR_EXISTING_FORM_PLACEHOLDER_TEXT: "Select New  or Existing",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_NEW: "New",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_EXISTING: "Existing",

  //Parent or Coach form
  PARENT_OR_COACH_FORM_LABEL_TEXT:"Parent or Coach?",
  PARENT_OR_COACH_FORM_HELP_TEXT:"Select whether you are a parent or coach",
  PARENT_OR_COACH_FORM_PLACEHOLDER_TEXT:"Select Parent or Coach",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_PARENT: "Parent",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_COACH: "Coach",

  //Registration form
  REGISTRATION_FORM_TITLE:"Student Details",
  REGISTRATION_FORM_SELECT:"Select...",
  REGISTRATION_FORM_YES:"Yes",
  REGISTRATION_FORM_NO:"No",
  REGISTRATION_FORM_SOME:"Some",
  REGISTRATION_FORM_FirstName_LABEL:"First Name",
  REGISTRATION_FORM_FirstName_PLACEHOLDER:"Enter First Name",
  REGISTRATION_FORM_FirstName_HELPTEXT:"Enter First Name",
  REGISTRATION_FORM_MiddleName_LABEL:"Middle Name",
  REGISTRATION_FORM_MiddleName_PLACEHOLDER:"Enter Middle Name",
  REGISTRATION_FORM_MiddleName_HELPTEXT:"Enter Middle Name",
  REGISTRATION_FORM_LastName_LABEL:"Last Name",
  REGISTRATION_FORM_LastName_PLACEHOLDER:"Enter Last Name",
  REGISTRATION_FORM_LastName_HELPTEXT:"Enter Last Name",
  REGISTRATION_FORM_SchoolName_LABEL:"School Name",
  REGISTRATION_FORM_SchoolName_PLACEHOLDER:"Enter School Name",
  REGISTRATION_FORM_SchoolName_HELPTEXT:"Select School Name",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE:"Site Type",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_SCHOOL:"School",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_PARK:"Park",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_COMMUNITY_CENTER:"Community Center",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_REGION:"Region",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_SCHOOL_NAME:"School Name",
  REGISTRATION_FORM_PersonalEmail_LABEL:"Personal Email",
  REGISTRATION_FORM_PersonalEmail_PLACEHOLDER:"Enter Personal Email",
  REGISTRATION_FORM_PersonalEmail_HELPTEXT:"Enter Personal Email",
  REGISTRATION_FORM_HomePhone_LABEL:"Home Phone",
  REGISTRATION_FORM_HomePhone_PLACEHOLDER:"Enter Home Phone",
  REGISTRATION_FORM_HomePhone_HELPTEXT:"Enter Home Phone",
  REGISTRATION_FORM_Birthdate_LABEL:"Birthdate",
  REGISTRATION_FORM_Birthdate_PLACEHOLDER:"Enter Birthdate",
  REGISTRATION_FORM_Birthdate_HELPTEXT:"Enter Birthdate",
  REGISTRATION_FORM_Gender_LABEL:"Gender",
  REGISTRATION_FORM_Gender_PLACEHOLDER:"Select Gender",
  REGISTRATION_FORM_Gender_HELPTEXT:"Select Gender",
  REGISTRATION_FORM_Gender_VALUE_MALE:"Male",
  REGISTRATION_FORM_Gender_VALUE_FEMALE:"Female",
  REGISTRATION_FORM_Gender_VALUE_NON_BINARY:"Non-binary",
  REGISTRATION_FORM_Gender_VALUE_PREFER_NOT_TO_SAY:"Prefer not to say",
  REGISTRATION_FORM_Grade_LABEL:"Grade",
  REGISTRATION_FORM_Grade_PLACEHOLDER:"Select Grade",
  REGISTRATION_FORM_Grade_HELPTEXT:"Select Grade",
  REGISTRATION_FORM_Grade_Kindergarten:"Kindergarten",
  REGISTRATION_FORM_Grade_First:"First",
  REGISTRATION_FORM_Grade_Second:"Second",
  REGISTRATION_FORM_Grade_Third:"Third",
  REGISTRATION_FORM_Grade_Fourth:"Fourth",
  REGISTRATION_FORM_Grade_Fifth:"Fifth",
  REGISTRATION_FORM_Grade_Sixth:"Sixth",
  REGISTRATION_FORM_Grade_Seventh:"Seventh",
  REGISTRATION_FORM_Grade_Eighth:"Eighth",
  REGISTRATION_FORM_Ethnicity_LABEL:"Ethnicity",
  REGISTRATION_FORM_Ethnicity_PLACEHOLDER:"Select Ethnicity",
  REGISTRATION_FORM_Ethnicity_HELPTEXT:"Select Ethnicity",
  REGISTRATION_FORM_Ethnicity_Hispanic_Latino:"Hispanic/Latino",
  REGISTRATION_FORM_Ethnicity_Native_American:"Native American",
  REGISTRATION_FORM_Ethnicity_African_American:"African American",
  REGISTRATION_FORM_Ethnicity_Pacific_Islander:"Pacific Islander",
  REGISTRATION_FORM_Ethnicity_Asian:"Asian",
  REGISTRATION_FORM_Ethnicity_Caucasian:"Caucasian",
  REGISTRATION_FORM_Ethnicity_Middle_Eastern_Arabic:"Middle Eastern/Arabic",
  REGISTRATION_FORM_Ethnicity_Multi_Racial_Multi_Ethnic:"Multi-Racial/Multi-Ethnic",
  REGISTRATION_FORM_Ethnicity_Filipino:"Filipino",
  REGISTRATION_FORM_Ethnicity_Other:"Other",
  REGISTRATION_FORM_ReducedPriceLunch_LABEL:"Reduced Price Lunch",
  REGISTRATION_FORM_ReducedPriceLunch_PLACEHOLDER:"Select Reduced Price Lunch",
  REGISTRATION_FORM_ReducedPriceLunch_HELPTEXT:"Select Reduced Price Lunch",
  REGISTRATION_FORM_Allergies_LABEL:"Allergies/Medical Conditions",
  REGISTRATION_FORM_Allergies_PLACEHOLDER:"Enter Allergies/Medical Conditions",
  REGISTRATION_FORM_Allergies_HELPTEXT:"Enter Allergies/Medical Conditions",
  REGISTRATION_FORM_PermissiontoCommuteAlone_LABEL:"Select Permission to Commute Alone",
  REGISTRATION_FORM_PermissiontoCommuteAlone_PLACEHOLDER:"Select Permission to Commute Alone",
  REGISTRATION_FORM_PermissiontoCommuteAlone_HELPTEXT:"Select Permission to Commute Alone",
  REGISTRATION_FORM_ParentFName_LABEL:"Parent First Name",
  REGISTRATION_FORM_ParentFName_PLACEHOLDER:"Enter Parent First Name",
  REGISTRATION_FORM_ParentFName_HELPTEXT:"Enter Parent First Name",
  REGISTRATION_FORM_ParentLName_LABEL:"Parent Last Name",
  REGISTRATION_FORM_ParentLName_PLACEHOLDER:"Enter Parent Last Name",
  REGISTRATION_FORM_ParentLName_HELPTEXT:"Enter Parent Last Name",
  REGISTRATION_FORM_ParentEmail_LABEL:"Parent Email",
  REGISTRATION_FORM_ParentEmail_PLACEHOLDER:"Enter Parent Email",
  REGISTRATION_FORM_ParentEmail_HELPTEXT:"Enter Parent Email",
  REGISTRATION_FORM_Relationship_LABEL:"Relationship to Child",
  REGISTRATION_FORM_Relationship_PLACEHOLDER:"Enter Relationship to Child",
  REGISTRATION_FORM_Relationship_HELPTEXT:"Enter Relationship to Child",
  REGISTRATION_FORM_ParentPhone1_LABEL:"Parent Phone 1",
  REGISTRATION_FORM_ParentPhone1_PLACEHOLDER:"Enter Parent Phone 1",
  REGISTRATION_FORM_ParentPhone1_HELPTEXT:"Enter Parent Phone 1",
  REGISTRATION_FORM_ParentPhone2_LABEL:"Parent Phone 2",
  REGISTRATION_FORM_ParentPhone2_PLACEHOLDER:"Enter Parent Phone 2",
  REGISTRATION_FORM_ParentPhone2_HELPTEXT:"Enter Parent Phone 2",
  REGISTRATION_FORM_ParentPhone3_LABEL:"Parent Phone 3",
  REGISTRATION_FORM_ParentPhone3_PLACEHOLDER:"Enter Parent Phone 3",
  REGISTRATION_FORM_ParentPhone3_HELPTEXT:"Enter Parent Phone 3",
  REGISTRATION_FORM_MailingStreet_LABEL:"Mailing Street",
  REGISTRATION_FORM_MailingStreet_PLACEHOLDER:"Enter Mailing Street",
  REGISTRATION_FORM_MailingStreet_HELPTEXT:"Enter Mailing Street",
  REGISTRATION_FORM_MailingCity_LABEL:"Mailing City",
  REGISTRATION_FORM_MailingCity_PLACEHOLDER:"Enter Mailing City",
  REGISTRATION_FORM_MailingCity_HELPTEXT:"Enter Mailing City",
  REGISTRATION_FORM_MailingState_LABEL:"Mailing State/Province",
  REGISTRATION_FORM_MailingState_PLACEHOLDER:"Enter Mailing State/Province",
  REGISTRATION_FORM_MailingState_HELPTEXT:"Enter Mailing State/Province",
  REGISTRATION_FORM_MailingZip_LABEL:"Mailing Zip",
  REGISTRATION_FORM_MailingZip_PLACEHOLDER:"Enter Mailing Zip",
  REGISTRATION_FORM_MailingZip_HELPTEXT:"Enter Mailing Zip",
  REGISTRATION_FORM_MailingCountry_LABEL:"Mailing Country",
  REGISTRATION_FORM_MailingCountry_PLACEHOLDER:"Enter Mailing Country",
  REGISTRATION_FORM_MailingCountry_HELPTEXT:"Enter Mailing Country",
  REGISTRATION_FORM_ParentEnglishFluency_LABEL:"Parent English Fluency",
  REGISTRATION_FORM_ParentEnglishFluency_PLACEHOLDER:"Select Parent English Fluency",
  REGISTRATION_FORM_ParentEnglishFluency_HELPTEXT:"Select Parent English Fluency",
  REGISTRATION_FORM_ParentHomeLang_LABEL:"Parent Home Language",
  REGISTRATION_FORM_ParentHomeLang_PLACEHOLDER:"Select Parent Home Language",
  REGISTRATION_FORM_ParentHomeLang_HELPTEXT:"Select Parent Home Language",
  REGISTRATION_FORM_Volunteer_LABEL:"Volunteer for this program? (Parent)",
  REGISTRATION_FORM_Volunteer_PLACEHOLDER:"Select Parent Home Language",
  REGISTRATION_FORM_Volunteer_HELPTEXT:"Select Volunteer for this Program",
  REGISTRATION_FORM_Emergency_Contact_Name_LABEL:"Emergency Contact Name",
  REGISTRATION_FORM_Emergency_Contact_Name_PLACEHOLDER:"Enter Emergency Contact Name",
  REGISTRATION_FORM_Emergency_Contact_Name_HELPTEXT:"Enter Emergency Contact Name",
  REGISTRATION_FORM_Emergency_Contact_Relationship_LABEL:"Emergency Relationship to Child",
  REGISTRATION_FORM_Emergency_Contact_Relationship_PLACEHOLDER:"Enter Emergency Relationship to Child",
  REGISTRATION_FORM_Emergency_Contact_Relationship_HELPTEXT:"Enter Emergency Relationship to Child",
  REGISTRATION_FORM_Emergency_Contact_Phone1_LABEL:"Emergency Phone 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_PLACEHOLDER:"Enter Emergency Phone 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_HELPTEXT:"Enter Emergency Phone 1",
  REGISTRATION_FORM_Emergency_Contact_Phone2_LABEL:"Emergency Phone 2",
  REGISTRATION_FORM_Emergency_Contact_Phone2_PLACEHOLDER:"Enter Emergency Phone 2",
  REGISTRATION_FORM_Emergency_Contact_Phone2_HELPTEXT:"Enter Emergency Phone 2",
  REGISTRATION_FORM_Emergency_Contact_Phone3_LABEL:"Emergency Phone 3",
  REGISTRATION_FORM_Emergency_Contact_Phone3_PLACEHOLDER:"Enter Emergency Phone 3",
  REGISTRATION_FORM_Emergency_Contact_Phone3_HELPTEXT:"Enter Emergency Phone 3",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_LABEL:"Permission to Pick up Child?",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER:"Select Permission to Pick up Child",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT:"Select Permission to Pick up Child",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_LABEL:"Secondary Emergency Contact Name",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_PLACEHOLDER:"Enter Secondary Emergency Contact Name",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_HELPTEXT:"Enter Secondary Emergency Contact Name",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_LABEL:"Secondary Emergency Relationship to Child",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_PLACEHOLDER:"Enter Secondary Emergency Relationship to Child",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_HELPTEXT:"Enter Secondary Emergency Relationship to Child",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_LABEL:"Secondary Emergency Phone 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_PLACEHOLDER:"Enter Secondary Emergency Phone 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_HELPTEXT:"Enter Secondary Emergency Phone 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_LABEL:"Secondary Emergency Phone 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_PLACEHOLDER:"Enter Secondary Emergency Phone 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_HELPTEXT:"Enter Secondary Emergency Phone 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_LABEL:"Secondary Emergency Phone 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_PLACEHOLDER:"Enter Secondary Emergency Phone 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_HELPTEXT:"Enter Secondary Emergency Phone 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_LABEL:"Secondary Permission to Pick up Child?",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER:"Select Secondary Permission to Pick up Child",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT:"Select Secondary Permission to Pick up Child",
};

export default localization_en;