const localization_es = {

  //Required Text
  REQUIRED_FIELD_REQUIRED_TEXT:"Requerido",
  REQUIRED_FIELD_VALID_TEXT:"Válido",
  REQUIRED_FIELD_TEXT_VALUE:"Texto",
  REQUIRED_FIELD_VALUE_VALUE:"Valor",
  REQUIRED_FIELD_EMAIL_VALUE:"Correo electrónico",
  REQUIRED_FIELD_NUMBER_VALUE:"Número",
  REQUIRED_FIELD_TELEPHONE_VALUE:"Teléfono",
  REQUIRED_FIELD_DATE_VALUE:"Fecha",

  //Language form
  LANGUAGE_FORM_LABEL_TEXT: "Idioma",
  LANGUAGE_FORM_HELP_TEXT: "Seleccione el idioma",
  LANGUAGE_FORM_PLACEHOLDER_TEXT: "Seleccione el idioma",

  //Firebase Authentication
  FIREBASE_AUTHENTICATION_SIGN_OUT_BUTTON_TEXT:"Desconectar",
  FIREBASE_AUTHENTICATION_SIGNING_OUT_BUTTON_TEXT:"Cerrando sesión",

  //New or Existing form
  NEW_OR_EXISTING_FORM_LABEL_TEXT: "¿Nuevo o existente?",
  NEW_OR_EXISTING_FORM_HELP_TEXT: "Seleccione si estás comenzando un nuevo registro de participante o actualizando un registro de estudiante existente",
  NEW_OR_EXISTING_FORM_PLACEHOLDER_TEXT: "Seleccione Nuevo o Existente",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_NEW: "Nuevo",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_EXISTING: "Existente",

  //Parent or Coach form
  PARENT_OR_COACH_FORM_LABEL_TEXT: "¿Padre/guardian o entrenador?",
  PARENT_OR_COACH_FORM_HELP_TEXT: "Seleccione si es padre/guardian o entrenador",
  PARENT_OR_COACH_FORM_PLACEHOLDER_TEXT: "Seleccionar padre o entrenador",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_PARENT: "Padre/Guardian",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_COACH: "Entrenador",

  //Registration form
  REGISTRATION_FORM_TITLE: "Detalles del participante",
  REGISTRATION_FORM_SELECT:"Seleccione...",
  REGISTRATION_FORM_YES:"Sí",
  REGISTRATION_FORM_NO:"No",
  REGISTRATION_FORM_SOME:"Algunos",
  REGISTRATION_FORM_Year_LABEL:"Año",
  REGISTRATION_FORM_Month_LABEL:"Mes",
  REGISTRATION_FORM_Day_LABEL:"Día",
  REGISTRATION_FORM_FirstName_LABEL: "Primer nombre",
  REGISTRATION_FORM_FirstName_PLACEHOLDER: "Ingrese el nombre del participante",
  REGISTRATION_FORM_FirstName_HELPTEXT: "Ingrese el nombre del participante",
  REGISTRATION_FORM_MiddleName_LABEL: "Segundo nombre",
  REGISTRATION_FORM_MiddleName_PLACEHOLDER: "Ingrese el segundo nombre",
  REGISTRATION_FORM_MiddleName_HELPTEXT: "Ingrese el segundo nombre",
  REGISTRATION_FORM_LastName_LABEL: "Apellido",
  REGISTRATION_FORM_LastName_PLACEHOLDER: "Ingrese el apellido",
  REGISTRATION_FORM_LastName_HELPTEXT: "Ingrese el apellido",
  REGISTRATION_FORM_SchoolName_LABEL: "Nombre de escuela",
  REGISTRATION_FORM_SchoolName_PLACEHOLDER: "Seleccione el nombre de la escuela",
  REGISTRATION_FORM_SchoolName_HELPTEXT: "Seleccione el nombre de la escuela",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE:"Tipo de sitio",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_SCHOOL:"Escuela",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_PARK:"parque",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_COMMUNITY_CENTER:"Centro Comunitario",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_REGION:"Región",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_SCHOOL_NAME:"Nombre de escuela",
  REGISTRATION_FORM_PersonalEmail_LABEL: "Email del estudiante",
  REGISTRATION_FORM_PersonalEmail_PLACEHOLDER: "Ingrese el correo electrónico del estudiante ",
  REGISTRATION_FORM_PersonalEmail_HELPTEXT: "Ingrese el correo electrónico del estudiante ",
  REGISTRATION_FORM_HomePhone_LABEL: "Teléfono del estudiante",
  REGISTRATION_FORM_HomePhone_PLACEHOLDER: "Ingrese el teléfono del estudiante",
  REGISTRATION_FORM_HomePhone_HELPTEXT: "Ingrese el teléfono del estudiante",
  REGISTRATION_FORM_Birthdate_LABEL: "Fecha de nacimiento",
  REGISTRATION_FORM_Birthdate_PLACEHOLDER: "Ingrese la fecha de nacimiento",
  REGISTRATION_FORM_Birthdate_HELPTEXT: "Ingrese la fecha de nacimiento",
  REGISTRATION_FORM_Gender_LABEL: "Género",
  REGISTRATION_FORM_Gender_PLACEHOLDER: "Seleccione género",
  REGISTRATION_FORM_Gender_HELPTEXT: "Seleccione género",
  REGISTRATION_FORM_Gender_VALUE_MALE:"Masculino",
  REGISTRATION_FORM_Gender_VALUE_FEMALE:"Feminino",
  REGISTRATION_FORM_Gender_VALUE_NON_BINARY:"No binario",
  REGISTRATION_FORM_Gender_VALUE_PREFER_NOT_TO_SAY:"Prefiero no decir",
  REGISTRATION_FORM_Grade_LABEL: "Nivel de grado",
  REGISTRATION_FORM_Grade_PLACEHOLDER: "Seleccione grado",
  REGISTRATION_FORM_Grade_HELPTEXT: "Seleccione grado",
  REGISTRATION_FORM_Grade_Kindergarten:"K",
  REGISTRATION_FORM_Grade_First:"1st",
  REGISTRATION_FORM_Grade_Second:"2nd",
  REGISTRATION_FORM_Grade_Third:"3rd",
  REGISTRATION_FORM_Grade_Fourth:"4th",
  REGISTRATION_FORM_Grade_Fifth:"5th",
  REGISTRATION_FORM_Grade_Sixth:"6th",
  REGISTRATION_FORM_Grade_Seventh:"7th",
  REGISTRATION_FORM_Grade_Eighth:"8th",
  REGISTRATION_FORM_Ethnicity_LABEL: "Etnicidad",
  REGISTRATION_FORM_Ethnicity_PLACEHOLDER: "Seleccionar origen étnico",
  REGISTRATION_FORM_Ethnicity_HELPTEXT: "Seleccionar origen étnico",
  REGISTRATION_FORM_Ethnicity_Hispanic_Latino:"Hispano/Latino",
  REGISTRATION_FORM_Ethnicity_Native_American:"Nativo americano",
  REGISTRATION_FORM_Ethnicity_African_American:"Afroamericano",
  REGISTRATION_FORM_Ethnicity_Pacific_Islander:"Isleño del pacífico",
  REGISTRATION_FORM_Ethnicity_Asian:"Asiático",
  REGISTRATION_FORM_Ethnicity_Caucasian:"Caucásico",
  REGISTRATION_FORM_Ethnicity_Middle_Eastern_Arabic:"Arabe de Medio Oriente",
  REGISTRATION_FORM_Ethnicity_Multi_Racial_Multi_Ethnic:"Multi Racial Multi étnico",
  REGISTRATION_FORM_Ethnicity_Filipino:"Filipino",
  REGISTRATION_FORM_Ethnicity_Other:"Otro",
  REGISTRATION_FORM_ReducedPriceLunch_LABEL: "¿Recibe su hijo(a) almuerzo gratis/costo reducido? ",
  REGISTRATION_FORM_ReducedPriceLunch_PLACEHOLDER: "Seleccione si recibe almuerzo a costo reducido",
  REGISTRATION_FORM_ReducedPriceLunch_HELPTEXT: "Seleccione si recibe almuerzo a costo reducido",
  REGISTRATION_FORM_Allergies_LABEL: "Alergias / Condiciones médicas",
  REGISTRATION_FORM_Allergies_PLACEHOLDER: "Ingrese alergias / condiciones médicas",
  REGISTRATION_FORM_Allergies_HELPTEXT: "Ingrese alergias / condiciones médicas",
  REGISTRATION_FORM_PermissiontoCommuteAlone_LABEL:"Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_PermissiontoCommuteAlone_PLACEHOLDER:"Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_PermissiontoCommuteAlone_HELPTEXT:"Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_ParentGuardianInformation_TITLE:"Información del padre / guardian",
  REGISTRATION_FORM_ParentFName_LABEL: "Nombre del padre",
  REGISTRATION_FORM_ParentFName_PLACEHOLDER: "Ingrese el nombre del padre/guardian",
  REGISTRATION_FORM_ParentFName_HELPTEXT: "Ingrese el nombre del padre/guardian",
  REGISTRATION_FORM_ParentLName_LABEL: "Apellido del padre/guardian",
  REGISTRATION_FORM_ParentLName_PLACEHOLDER: "Ingrese el apellido del padre/guardian",
  REGISTRATION_FORM_ParentLName_HELPTEXT: "Ingrese el apellido del padre/guardian",
  REGISTRATION_FORM_ParentEmail_LABEL: "Correo electrónico de padre/guardian",
  REGISTRATION_FORM_ParentEmail_PLACEHOLDER: "Ingrese el correo electrónico de padre/guardian",
  REGISTRATION_FORM_ParentEmail_HELPTEXT: "Ingrese el correo electrónico de padre/guardian",
  REGISTRATION_FORM_Relationship_LABEL: "Relacion al estudiante",
  REGISTRATION_FORM_Relationship_PLACEHOLDER: "Ingrese la relación al estudiante",
  REGISTRATION_FORM_Relationship_HELPTEXT: "Ingrese la relación al estudiante",
  REGISTRATION_FORM_Relationship_VALUE_Parent:"Padre",
  REGISTRATION_FORM_Relationship_VALUE_LegalGuardian:"Guardián legal",
  REGISTRATION_FORM_Relationship_VALUE_FosterParent:"Padre adoptivo",
  REGISTRATION_FORM_Relationship_VALUE_Grandparent:"Abuelo",
  REGISTRATION_FORM_Relationship_VALUE_SiblingOrOtherRelative:"Hermano / otro familiar",
  REGISTRATION_FORM_ParentPhone1_LABEL: "Teléfono de padre/guardian 1",
  REGISTRATION_FORM_ParentPhone1_PLACEHOLDER: "Ingrese el primario teléfono de padre/guardian",
  REGISTRATION_FORM_ParentPhone1_HELPTEXT: "Ingrese el primario teléfono de padre/guardian",
  REGISTRATION_FORM_ParentPhone2_LABEL: "Teléfono de padre/guardian 2",
  REGISTRATION_FORM_ParentPhone2_PLACEHOLDER: "Ingrese el segundario teléfono de padre/guardian",
  REGISTRATION_FORM_ParentPhone2_HELPTEXT: "Ingrese el segundario teléfono de padre/guardian",
  REGISTRATION_FORM_MailingStreet_LABEL: "Direccion de casa",
  REGISTRATION_FORM_MailingStreet_PLACEHOLDER: "Ingrese la direccion de casa",
  REGISTRATION_FORM_MailingStreet_HELPTEXT: "Ingrese la direccion de casa",
  REGISTRATION_FORM_MailingCity_LABEL: "Ciudad",
  REGISTRATION_FORM_MailingCity_PLACEHOLDER: "Ingrese la ciudad",
  REGISTRATION_FORM_MailingCity_HELPTEXT: "Ingrese la ciudad",
  REGISTRATION_FORM_MailingState_LABEL: "Estado / provincia",
  REGISTRATION_FORM_MailingState_PLACEHOLDER: "Ingrese el estado / provincia",
  REGISTRATION_FORM_MailingState_HELPTEXT: "Ingrese el estado / provincia",
  REGISTRATION_FORM_MailingZip_LABEL: "Código Postal",
  REGISTRATION_FORM_MailingZip_PLACEHOLDER: "Ingrese el código postal",
  REGISTRATION_FORM_MailingZip_HELPTEXT: "Ingrese el código postal",
  REGISTRATION_FORM_MailingCountry_LABEL: "País",
  REGISTRATION_FORM_MailingCountry_PLACEHOLDER: "Ingrese el país",
  REGISTRATION_FORM_MailingCountry_HELPTEXT: "Ingrese el país",
  REGISTRATION_FORM_ParentEnglishFluency_LABEL:"Fluidez en inglés del padre / guardian",
  REGISTRATION_FORM_ParentEnglishFluency_PLACEHOLDER:"Seleccionar fluidez en inglés para padres / guardian",
  REGISTRATION_FORM_ParentEnglishFluency_HELPTEXT:"Seleccionar fluidez en inglés para padres / guardian",
  REGISTRATION_FORM_ParentHomeLang_LABEL: "Idioma hablado en casa",
  REGISTRATION_FORM_ParentHomeLang_PLACEHOLDER: "Seleccione el idioma hablado en casa",
  REGISTRATION_FORM_ParentHomeLang_HELPTEXT: "Seleccione el idioma hablado en casa",
  REGISTRATION_FORM_ParentHomeLang_English:"Inglés",
  REGISTRATION_FORM_ParentHomeLang_Spanish:"Español",
  REGISTRATION_FORM_ParentHomeLang_Chinese:"Chino (incluido Cantonés, Mandarín y otros idiomas chinos)",
  REGISTRATION_FORM_ParentHomeLang_Arabic:"Arábica",
  REGISTRATION_FORM_ParentHomeLang_Bengali:"Bengalí",
  REGISTRATION_FORM_ParentHomeLang_French:"Francés y criollo Francés",
  REGISTRATION_FORM_ParentHomeLang_German:"Alemán",
  REGISTRATION_FORM_ParentHomeLang_Greek:"Griego",
  REGISTRATION_FORM_ParentHomeLang_Gujarati:"Gujarati",
  REGISTRATION_FORM_ParentHomeLang_Hebrew:"Hebreo",
  REGISTRATION_FORM_ParentHomeLang_Hindi:"Hindi",
  REGISTRATION_FORM_ParentHomeLang_Hmong:"Hmong",
  REGISTRATION_FORM_ParentHomeLang_Italian:"Italiano",
  REGISTRATION_FORM_ParentHomeLang_Japanese:"Japonés",
  REGISTRATION_FORM_ParentHomeLang_Korean:"Coreano",
  REGISTRATION_FORM_ParentHomeLang_Punjabi:"Punjabi",
  REGISTRATION_FORM_ParentHomeLang_Persian:"Persa",
  REGISTRATION_FORM_ParentHomeLang_Polish:"Polaco",
  REGISTRATION_FORM_ParentHomeLang_Portuguese:"Portugués",
  REGISTRATION_FORM_ParentHomeLang_Russian:"Ruso",
  REGISTRATION_FORM_ParentHomeLang_Tagalog:"Tagalo",
  REGISTRATION_FORM_ParentHomeLang_Telugu:"Telugu",
  REGISTRATION_FORM_ParentHomeLang_Urdu:"Urdu",
  REGISTRATION_FORM_ParentHomeLang_Vietnamese:"Vietnamita",
  REGISTRATION_FORM_ParentHomeLang_Other:"Otro",
  REGISTRATION_FORM_Volunteer_LABEL: "¿Le gustaría ser voluntario para este programa?",
  REGISTRATION_FORM_Volunteer_PLACEHOLDER: "¿Le gustaría ser voluntario para este programa?",
  REGISTRATION_FORM_Volunteer_HELPTEXT: "¿Le gustaría ser voluntario para este programa?",
  REGISTRATION_FORM_Emergency_Contact_Name_LABEL: "Contacto en caso de emergencia (otro que no sea padre/guardian)",
  REGISTRATION_FORM_Emergency_Contact_TITLE:"Contacto de emergencia (que no sea el padre / guardian)",
  REGISTRATION_FORM_Emergency_Contact_Name_PLACEHOLDER: "Ingrese el nombre del contacto",
  REGISTRATION_FORM_Emergency_Contact_Name_HELPTEXT: "Ingrese el nombre del contacto",
  REGISTRATION_FORM_Emergency_Contact_Relationship_LABEL: "Relación al participante",
  REGISTRATION_FORM_Emergency_Contact_Relationship_PLACEHOLDER: "Ingrese la relación al participante",
  REGISTRATION_FORM_Emergency_Contact_Relationship_HELPTEXT: "Ingrese la relación al participante",
  REGISTRATION_FORM_Emergency_Contact_Phone1_LABEL: "Teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_PLACEHOLDER: "Ingrese el teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_HELPTEXT: "Ingrese el teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone2_LABEL: "Contacto secundario en caso de emergencia (otro que no sea padre/guardian)",
  REGISTRATION_FORM_Emergency_Contact_Phone2_PLACEHOLDER: "Ingrese el teléfono de emergencia 2",
  REGISTRATION_FORM_Emergency_Contact_Phone2_HELPTEXT: "Ingrese el teléfono de emergencia 2",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_LABEL: "¿Permiso para recoger al niño?",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER: "Seleccionar permiso para recoger al niño",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT: "Seleccionar permiso para recoger al niño",
  REGISTRATION_FORM_Second_Emergency_Contact_TITLE:"Nombre del contacto de emergencia secundario (otro que no sea padre/guardian)",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_LABEL: "Nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_PLACEHOLDER: "Ingrese el nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_HELPTEXT: "Ingrese el nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_LABEL: "Relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_PLACEHOLDER: "Ingrese la relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_HELPTEXT: "Ingrese la relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_LABEL: "Teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_PLACEHOLDER: "Ingrese el teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_HELPTEXT: "Ingrese el teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_LABEL: "Teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_PLACEHOLDER: "Ingrese el teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_HELPTEXT: "Ingrese el teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_LABEL: "¿Permiso secundario para recoger al niño?",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER: "Seleccione Permiso secundario para recoger al niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT: "Seleccione Permiso secundario para recoger al niño",

  //REGISTRATION WAIVER
  REGISTRATION_FORM_WAIVER_MODAL_TITLE_TEXT:"Renuncia / Renuncias",
  REGISTRATION_FORM_WAIVER_REVIEW_AND_ACCEPT_REQUEST_MESSAGE:"Revise y acepte la exención : ",
  REGISTRATION_FORM_WAIVER_ACCEPT_BUTTON_TEXT:"Aceptar",
  REGISTRATION_FORM_WAIVER_DECLINE_BUTTON_TEXT:"Disminución",
  REGISTRATION_FORM_WAIVER_CLOSE_BUTTON_TEXT:"Cerca",
  REGISTRATION_FORM_WAIVER_SHOW_WAIVER_BUTTON_TEXT:"Mostrar renuncia",
  REGISTRATION_FORM_WAIVER_WAIVER_ACCEPTED_MESSAGE:"Renuncia aceptadas",
};

export default localization_es;
