const localization_es = {

  //Language form
  LANGUAGE_FORM_LABEL_TEXT: "Idioma",
  LANGUAGE_FORM_HELP_TEXT: "Seleccione el idioma",
  LANGUAGE_FORM_PLACEHOLDER_TEXT: "Seleccione el idioma",

  //New or Existing form
  NEW_OR_EXISTING_FORM_LABEL_TEXT: "¿Nuevo o existente?",
  NEW_OR_EXISTING_FORM_HELP_TEXT: "Seleccione si estás comenzando un nuevo registro de estudiante o actualizando un registro de estudiante existente",
  NEW_OR_EXISTING_FORM_PLACEHOLDER_TEXT: "Seleccione Nuevo o Existente",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_NEW: "Nuevo",
  NEW_OR_EXISTING_FORM_BUTTON_TEXT_EXISTING: "Existente",

  //Parent or Coach form
  PARENT_OR_COACH_FORM_LABEL_TEXT: "¿Padre o entrenador?",
  PARENT_OR_COACH_FORM_HELP_TEXT: "Seleccione si es padre o entrenador",
  PARENT_OR_COACH_FORM_PLACEHOLDER_TEXT: "Seleccionar padre o entrenador",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_PARENT: "Padre",
  PARENT_OR_COACH_FORM_BUTTON_TEXT_COACH: "Entrenador",

  //Registration form
  REGISTRATION_FORM_TITLE: "Detalles del estudiante",
  REGISTRATION_FORM_SELECT:"Seleccione...",
  REGISTRATION_FORM_YES:"Sí",
  REGISTRATION_FORM_NO:"No",
  REGISTRATION_FORM_SOME:"Algunos",
  REGISTRATION_FORM_FirstName_LABEL: "Primer nombre",
  REGISTRATION_FORM_FirstName_PLACEHOLDER: "Ingrese el nombre",
  REGISTRATION_FORM_FirstName_HELPTEXT: "Ingrese el nombre",
  REGISTRATION_FORM_MiddleName_LABEL: "Segundo nombre",
  REGISTRATION_FORM_MiddleName_PLACEHOLDER: "Ingrese el segundo nombre",
  REGISTRATION_FORM_MiddleName_HELPTEXT: "Ingrese el segundo nombre",
  REGISTRATION_FORM_LastName_LABEL: "Apellido",
  REGISTRATION_FORM_LastName_PLACEHOLDER: "Introduzca el apellido",
  REGISTRATION_FORM_LastName_HELPTEXT: "Introduzca el apellido",
  REGISTRATION_FORM_SchoolName_LABEL: "Nombre de escuela",
  REGISTRATION_FORM_SchoolName_PLACEHOLDER: "Ingrese el nombre de la escuela",
  REGISTRATION_FORM_SchoolName_HELPTEXT: "Seleccione el nombre de la escuela",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE:"Tipo de sitio",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_SCHOOL:"Escuela",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_PARK:"Parque",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_TYPE_COMMUNITY_CENTER:"Centro Comunitario",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_REGION:"Región",
  REGISTRATION_FORM_SchoolName_FIELD_SITE_SCHOOL_NAME:"Nombre de escuela",
  REGISTRATION_FORM_PersonalEmail_LABEL: "Email personal",
  REGISTRATION_FORM_PersonalEmail_PLACEHOLDER: "Ingrese su correo electrónico personal",
  REGISTRATION_FORM_PersonalEmail_HELPTEXT: "Ingrese su correo electrónico personal",
  REGISTRATION_FORM_HomePhone_LABEL: "Teléfono de casa",
  REGISTRATION_FORM_HomePhone_PLACEHOLDER: "Ingrese el teléfono de casa",
  REGISTRATION_FORM_HomePhone_HELPTEXT: "Ingrese el teléfono de casa",
  REGISTRATION_FORM_Birthdate_LABEL: "Fecha de nacimiento",
  REGISTRATION_FORM_Birthdate_PLACEHOLDER: "Ingrese la fecha de nacimiento",
  REGISTRATION_FORM_Birthdate_HELPTEXT: "Ingrese la fecha de nacimiento",
  REGISTRATION_FORM_Gender_LABEL: "Género",
  REGISTRATION_FORM_Gender_PLACEHOLDER: "Seleccione género",
  REGISTRATION_FORM_Gender_HELPTEXT: "Seleccione género",
  REGISTRATION_FORM_Gender_VALUE_MALE:"Masculino",
  REGISTRATION_FORM_Gender_VALUE_FEMALE:"Mujer",
  REGISTRATION_FORM_Gender_VALUE_NON_BINARY:"No binario",
  REGISTRATION_FORM_Gender_VALUE_PREFER_NOT_TO_SAY:"Prefiero no decirlo",
  REGISTRATION_FORM_Grade_LABEL: "Calificación",
  REGISTRATION_FORM_Grade_PLACEHOLDER: "Seleccionar grado",
  REGISTRATION_FORM_Grade_HELPTEXT: "Seleccionar grado",
  REGISTRATION_FORM_Grade_Kindergarten:"Jardín de infancia",
  REGISTRATION_FORM_Grade_First:"Primero",
  REGISTRATION_FORM_Grade_Second:"Segundo",
  REGISTRATION_FORM_Grade_Third:"Tercero",
  REGISTRATION_FORM_Grade_Fourth:"Cuarto",
  REGISTRATION_FORM_Grade_Fifth:"Quinto",
  REGISTRATION_FORM_Grade_Sixth:"Sexto",
  REGISTRATION_FORM_Grade_Seventh:"Séptimo",
  REGISTRATION_FORM_Grade_Eighth:"Octavo",
  REGISTRATION_FORM_Ethnicity_LABEL: "Etnicidad",
  REGISTRATION_FORM_Ethnicity_PLACEHOLDER: "Seleccionar origen étnico",
  REGISTRATION_FORM_Ethnicity_HELPTEXT: "Seleccionar origen étnico",
  REGISTRATION_FORM_Ethnicity_Hispanic_Latino:"Hispano / latino",
  REGISTRATION_FORM_Ethnicity_Native_American:"Nativo americano",
  REGISTRATION_FORM_Ethnicity_African_American:"afroamericano",
  REGISTRATION_FORM_Ethnicity_Pacific_Islander:"Isleño del pacífico",
  REGISTRATION_FORM_Ethnicity_Asian:"asiático",
  REGISTRATION_FORM_Ethnicity_Caucasian:"caucásico",
  REGISTRATION_FORM_Ethnicity_Middle_Eastern_Arabic:"Middle_Eastern_Arabic",
  REGISTRATION_FORM_Ethnicity_Multi_Racial_Multi_Ethnic:"Multi_Racial_Multi_Ethnic",
  REGISTRATION_FORM_Ethnicity_Filipino:"Filipino",
  REGISTRATION_FORM_Ethnicity_Other:"Otro",
  REGISTRATION_FORM_ReducedPriceLunch_LABEL: "Almuerzo a precio reducido",
  REGISTRATION_FORM_ReducedPriceLunch_PLACEHOLDER: "Seleccionar almuerzo a precio reducido",
  REGISTRATION_FORM_ReducedPriceLunch_HELPTEXT: "Seleccionar almuerzo a precio reducido",
  REGISTRATION_FORM_Allergies_LABEL: "Alergias / Condiciones médicas",
  REGISTRATION_FORM_Allergies_PLACEHOLDER: "Ingrese alergias / condiciones médicas",
  REGISTRATION_FORM_Allergies_HELPTEXT: "Ingrese alergias / condiciones médicas",
  REGISTRATION_FORM_PermissiontoCommuteAlone_LABEL: "Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_PermissiontoCommuteAlone_PLACEHOLDER: "Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_PermissiontoCommuteAlone_HELPTEXT: "Seleccionar permiso para viajar solo",
  REGISTRATION_FORM_ParentFName_LABEL: "Nombre del padre",
  REGISTRATION_FORM_ParentFName_PLACEHOLDER: "Ingrese el nombre del padre",
  REGISTRATION_FORM_ParentFName_HELPTEXT: "Ingrese el nombre del padre",
  REGISTRATION_FORM_ParentLName_LABEL: "Apellido del padre",
  REGISTRATION_FORM_ParentLName_PLACEHOLDER: "Ingrese el apellido del padre",
  REGISTRATION_FORM_ParentLName_HELPTEXT: "Ingrese el apellido del padre",
  REGISTRATION_FORM_ParentEmail_LABEL: "Correo electrónico de los padres",
  REGISTRATION_FORM_ParentEmail_PLACEHOLDER: "Ingrese el correo electrónico de los padres",
  REGISTRATION_FORM_ParentEmail_HELPTEXT: "Ingrese el correo electrónico de los padres",
  REGISTRATION_FORM_Relationship_LABEL: "Relacion hacía el niño",
  REGISTRATION_FORM_Relationship_PLACEHOLDER: "Ingrese la relación con el niño",
  REGISTRATION_FORM_Relationship_HELPTEXT: "Ingrese la relación con el niño",
  REGISTRATION_FORM_ParentPhone1_LABEL: "Teléfono de los padres 1",
  REGISTRATION_FORM_ParentPhone1_PLACEHOLDER: "Ingrese el teléfono de los padres 1",
  REGISTRATION_FORM_ParentPhone1_HELPTEXT: "Ingrese el teléfono de los padres 1",
  REGISTRATION_FORM_ParentPhone2_LABEL: "Teléfono de los padres 2",
  REGISTRATION_FORM_ParentPhone2_PLACEHOLDER: "Ingrese el teléfono de los padres 2",
  REGISTRATION_FORM_ParentPhone2_HELPTEXT: "Ingrese el teléfono de los padres 2",
  REGISTRATION_FORM_ParentPhone3_LABEL: "Teléfono de los padres 3",
  REGISTRATION_FORM_ParentPhone3_PLACEHOLDER: "Ingrese el teléfono de los padres 3",
  REGISTRATION_FORM_ParentPhone3_HELPTEXT: "Ingrese el teléfono de los padres 3",
  REGISTRATION_FORM_MailingStreet_LABEL: "Calle de correo",
  REGISTRATION_FORM_MailingStreet_PLACEHOLDER: "Ingrese a la calle de correo",
  REGISTRATION_FORM_MailingStreet_HELPTEXT: "Ingrese a la calle de correo",
  REGISTRATION_FORM_MailingCity_LABEL: "Ciudad de envío",
  REGISTRATION_FORM_MailingCity_PLACEHOLDER: "Ingrese la ciudad de envío",
  REGISTRATION_FORM_MailingCity_HELPTEXT: "Ingrese la ciudad de envío",
  REGISTRATION_FORM_MailingState_LABEL: "Estado / provincia de envío",
  REGISTRATION_FORM_MailingState_PLACEHOLDER: "Ingrese el estado / provincia de envío",
  REGISTRATION_FORM_MailingState_HELPTEXT: "Ingrese el estado / provincia de envío",
  REGISTRATION_FORM_MailingZip_LABEL: "Cremallera postal",
  REGISTRATION_FORM_MailingZip_PLACEHOLDER: "Ingrese el código postal",
  REGISTRATION_FORM_MailingZip_HELPTEXT: "Ingrese el código postal",
  REGISTRATION_FORM_MailingCountry_LABEL: "País de envío",
  REGISTRATION_FORM_MailingCountry_PLACEHOLDER: "Ingrese el país de envío",
  REGISTRATION_FORM_MailingCountry_HELPTEXT: "Ingrese el país de envío",
  REGISTRATION_FORM_ParentEnglishFluency_LABEL: "Fluidez en inglés de los padres",
  REGISTRATION_FORM_ParentEnglishFluency_PLACEHOLDER: "Seleccionar fluidez en inglés para padres",
  REGISTRATION_FORM_ParentEnglishFluency_HELPTEXT: "Seleccionar fluidez en inglés para padres",
  REGISTRATION_FORM_ParentHomeLang_LABEL: "Idioma del hogar de los padres",
  REGISTRATION_FORM_ParentHomeLang_PLACEHOLDER: "Seleccione el idioma materno de los padres",
  REGISTRATION_FORM_ParentHomeLang_HELPTEXT: "Seleccione el idioma materno de los padres",
  REGISTRATION_FORM_ParentHomeLang_English:"inglés",
  REGISTRATION_FORM_ParentHomeLang_Spanish:"Español",
  REGISTRATION_FORM_ParentHomeLang_Chinese:"Chino (incluido cantonés, mandarín y otros idiomas chinos)",
  REGISTRATION_FORM_ParentHomeLang_Arabic:"Arábica",
  REGISTRATION_FORM_ParentHomeLang_Bengali:"bengalí",
  REGISTRATION_FORM_ParentHomeLang_French:"Francés y criollo francés",
  REGISTRATION_FORM_ParentHomeLang_German:"alemán",
  REGISTRATION_FORM_ParentHomeLang_Greek:"griego",
  REGISTRATION_FORM_ParentHomeLang_Gujrati:"Gujrati",
  REGISTRATION_FORM_ParentHomeLang_Hebrew:"hebreo",
  REGISTRATION_FORM_ParentHomeLang_Hindi:"hindi",
  REGISTRATION_FORM_ParentHomeLang_Hmong:"Hmong",
  REGISTRATION_FORM_ParentHomeLang_Italian:"italiano",
  REGISTRATION_FORM_ParentHomeLang_Japanese:"japonés",
  REGISTRATION_FORM_ParentHomeLang_Korean:"coreano",
  REGISTRATION_FORM_ParentHomeLang_Punjabi:"punjabi",
  REGISTRATION_FORM_ParentHomeLang_Persian:"persa",
  REGISTRATION_FORM_ParentHomeLang_Polish:"polaco",
  REGISTRATION_FORM_ParentHomeLang_Portuguese:"portugués",
  REGISTRATION_FORM_ParentHomeLang_Russian:"ruso",
  REGISTRATION_FORM_ParentHomeLang_Tagalog:"Tagalo",
  REGISTRATION_FORM_ParentHomeLang_Telugu:"Telugu",
  REGISTRATION_FORM_ParentHomeLang_Urdu:"Urdu",
  REGISTRATION_FORM_ParentHomeLang_Vietnamese:"vietnamita",
  REGISTRATION_FORM_ParentHomeLang_Other:"Otro",
  REGISTRATION_FORM_Volunteer_LABEL: "¿Ser voluntario para este programa? (Padre)",
  REGISTRATION_FORM_Volunteer_PLACEHOLDER: "Seleccione el idioma materno de los padres",
  REGISTRATION_FORM_Volunteer_HELPTEXT: "Seleccione voluntario para este programa",
  REGISTRATION_FORM_Emergency_Contact_Name_LABEL: "nombre del contacto de emergencia",
  REGISTRATION_FORM_Emergency_Contact_Name_PLACEHOLDER: "Ingrese el nombre del contacto de emergencia",
  REGISTRATION_FORM_Emergency_Contact_Name_HELPTEXT: "Ingrese el nombre del contacto de emergencia",
  REGISTRATION_FORM_Emergency_Contact_Relationship_LABEL: "Relación de emergencia con el niño",
  REGISTRATION_FORM_Emergency_Contact_Relationship_PLACEHOLDER: "Ingrese Relación de emergencia con el niño",
  REGISTRATION_FORM_Emergency_Contact_Relationship_HELPTEXT: "Ingrese Relación de emergencia con el niño",
  REGISTRATION_FORM_Emergency_Contact_Phone1_LABEL: "Teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_PLACEHOLDER: "Ingrese el teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone1_HELPTEXT: "Ingrese el teléfono de emergencia 1",
  REGISTRATION_FORM_Emergency_Contact_Phone2_LABEL: "Teléfono de emergencia 2",
  REGISTRATION_FORM_Emergency_Contact_Phone2_PLACEHOLDER: "Ingrese el teléfono de emergencia 2",
  REGISTRATION_FORM_Emergency_Contact_Phone2_HELPTEXT: "Ingrese el teléfono de emergencia 2",
  REGISTRATION_FORM_Emergency_Contact_Phone3_LABEL: "Teléfono de emergencia 3",
  REGISTRATION_FORM_Emergency_Contact_Phone3_PLACEHOLDER: "Ingrese el teléfono de emergencia 3",
  REGISTRATION_FORM_Emergency_Contact_Phone3_HELPTEXT: "Ingrese el teléfono de emergencia 3",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_LABEL: "¿Permiso para recoger al niño?",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER: "Seleccionar permiso para recoger al niño",
  REGISTRATION_FORM_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT: "Seleccionar permiso para recoger al niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_LABEL: "Nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_PLACEHOLDER: "Ingrese el nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Name_HELPTEXT: "Ingrese el nombre del contacto de emergencia secundario",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_LABEL: "Relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_PLACEHOLDER: "Ingrese la relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Relationship_HELPTEXT: "Ingrese la relación de emergencia secundaria con el niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_LABEL: "Teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_PLACEHOLDER: "Ingrese el teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone1_HELPTEXT: "Ingrese el teléfono de emergencia secundario 1",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_LABEL: "Teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_PLACEHOLDER: "Ingrese el teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone2_HELPTEXT: "Ingrese el teléfono de emergencia secundario 2",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_LABEL: "Teléfono de emergencia secundario 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_PLACEHOLDER: "Ingrese el teléfono de emergencia secundario 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Phone3_HELPTEXT: "Ingrese el teléfono de emergencia secundario 3",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_LABEL: "¿Permiso secundario para recoger al niño?",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_PLACEHOLDER: "Seleccione Permiso secundario para recoger al niño",
  REGISTRATION_FORM_Second_Emergency_Contact_Permission_to_Pickup_child_HELPTEXT: "Seleccione Permiso secundario para recoger al niño"
};

export default localization_es;